version: '3.8'

networks:
  app:
    name: "${APP_NAME:-app}-network"
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    container_name: "nginx-${APP_NAME:-app}"
    depends_on:
      - php
    volumes:
      - '.:/var/www/html'
    ports:
      - '${APP_PORT:-80}:80'
    networks:
      - app
  php:
    build:
      context: .
      dockerfile: .docker/php.dockerfile
    container_name: "php-${APP_NAME:-app}"
    volumes:
      - '.:/var/www/html'
    networks:
      - app
  composer:
    build:
      context: .
      dockerfile: .docker/php.dockerfile
    container_name: "composer-${APP_NAME:-app}"
    entrypoint: [ "composer" ]
    volumes:
      - '.:/var/www/html'
    networks:
      - app

